### ISSUE TITLE
Can't parse maps (SanFrancisco)

### ISSUE THREAD

**Issue by Gowan1998** [safeautonomy/ComOpT#3]
Hey guys,
If I only use Apollo then I see the map and the car is driven correctly by the AI.
But if I use ComOpt then I don't see the San Francisco map in Dreamview nor is the car really navigated.

Because of that I deleted the content in ../scripts/output and try to parse the map again now (C. Map parsing).
nei4J is correct installed and the env variables are correct setted.
Apart from that, I can easily access my neo4j graph via http://localhost:7474/ given the information above (endpoint, usr, pw)
I followed exactly your description C. and everything is fine.
But now I can't run description A. nor description B. because the scenarios can't be found anymore.
Do you have any idea how to fix the problem?

Error message:
(rllib) shawan@shawan-System-Product-Name:~/code/ComOpT$ python3 scripts/ad_tester.py scripts/ad_tester_output
2022-06-07 10:39:07.847 | DEBUG    | comopt.map_parse.map_parse:load_map:90 - Start loading map
2022-06-07 10:39:08.369 | DEBUG    | comopt.map_parse.map_parse:load_map:96 - Finish loading map
2022-06-07 10:39:08.370 | INFO     | __main__:<module>:81 - Abstract scenarios found.
2022-06-07 10:39:08.411 | INFO     | __main__:<module>:112 - Concrete scenarios found.
2022-06-07 10:39:08.411 | INFO     | __main__:<module>:139 - Running scenario equiv_class_id=0, sample_id=0
Traceback (most recent call last):
  File "scripts/ad_tester.py", line 141, in <module>
    result = scenario_runner.exec()
  File "/home/shawan/code/ComOpT/scripts/comopt/scenario.py", line 293, in exec
    assert self.available, 'The scenario is unavailable'
AssertionError: The scenario is unavailable

**Comment by Gowan1998** [comment]
The error occurs at line 293 in scenario.py.
I have commented out this line and everything seems to run smoothly
